
FROM node:18.18.0-bookworm-slim

WORKDIR /app

ENV NODE_ENV production

COPY dist dist

# Vite build always runs in ESM.
RUN echo '{"type":"module"}' > ./dist/package.json

EXPOSE 3000

ENTRYPOINT ["node", "./dist/server/production.js"]
